### ISSUE TITLE
Orange pi5

### ISSUE THREAD

**Issue by Gazgiza** [jamsinclair/opifancontrol#1] opened 2024-03-26 12:54 UTC
Hi! Great job. But I only have an orange pi 5. Does it work for it?
Have a nice day

**Comment by dandycyclone** [comment] 2024-06-09 20:25
To my regret I did not manage to make it working with Orange Pi 5 and the problem is not with script or service, but with the board - might be only with my board. I will show:

```
Jun 09 12:31:21 pve systemd[1]: Started opifancontrol.service - Orange Pi Fan Control Service.
Jun 09 12:31:22 pve opifancontrol.sh[163921]: Starting opifancontrol...
Jun 09 12:31:22 pve opifancontrol.sh[163921]: PWM range: 192
Jun 09 12:31:22 pve opifancontrol.sh[163921]: PWM clock: 4
Jun 09 12:31:22 pve opifancontrol.sh[163921]: Fan GPIO pin: 2
Jun 09 12:31:22 pve opifancontrol.sh[163921]: Temperature poll interval: 2 seconds
Jun 09 12:31:22 pve opifancontrol.sh[163921]: Temperature thresholds (C): 55, 65, 70
Jun 09 12:31:22 pve opifancontrol.sh[163921]: Fan speed thresholds (%): 50, 75, 100
Jun 09 12:31:22 pve opifancontrol.sh[163921]: Ramp up delay: 15 seconds
Jun 09 12:31:22 pve opifancontrol.sh[163921]: Ramp down delay: 60 seconds

Jun 09 12:33:22 pve opifancontrol.sh[163921]: Changing Fan Speed | CPU temp: 58, target PWM: 96, current PWM: 0
Jun 09 12:33:22 pve opifancontrol.sh[164602]: gpio: CCR should be less than or equal to ARR (11)
```

The last string is the error returned by _gpio_ tool from [wiringOP](https://github.com/orangepi-xunlong/wiringOP/tree/next). It defines, that PWM duty cycle falls outside of the range, that was initialized at the service start time with value of 192 - "_PWM range: 192_". Further running the script in daemon mode only confirmed, that problem is not caused by the script itself - I was able to changing PWM duty cycle interactively sitting by the rotating fan and I clearly saw, that it worked... till some condition/event:

```
root@pve:/usr/local/bin# ./opifancontrol.sh &
[1] 168187
root@pve:/usr/local/bin# Starting opifancontrol...
PWM range: 192
PWM clock: 4
Fan GPIO pin: 2
Temperature poll interval: 2 seconds
Temperature thresholds (C): 55, 65, 70
Fan speed thresholds (%): 50, 75, 100
Ramp up delay: 15 seconds
Ramp down delay: 60 seconds

root@pve:/usr/local/bin# gpio pwm 2 96
root@pve:/usr/local/bin# gpio pwm 2 50
root@pve:/usr/local/bin# gpio pwm 2 180
root@pve:/usr/local/bin# gpio pwm 2 60
root@pve:/usr/local/bin# 
root@pve:/usr/local/bin# gpio pwm 2 60
gpio: CCR should be less than or equal to ARR (11)

Changing Fan Speed | CPU temp: 58, target PWM: 96, current PWM: 0
gpio: CCR should be less than or equal to ARR (11)
```

Here exact "_condition/event_" is not known to me - it is the moment, when auto-reload register (ARR) is updated with some "garbage" value of 11 (and always the same value). I paid attention, that interval between compare & capture register (CCR) updates is not important though - problem is manifested sporadically, however at the time, when CPU utilization (thus the temperature) is rapidly increasing.

All above tests were executed with PWM15 GPIO. I did not try others - official guide tells us, that "Orange Pi 5 includes pwm0, pwm1, pwm3, pwm13, pwm14 and pwm15, a total of six pwm".

For ref.: https://github.com/orangepi-xunlong/wiringOP/blob/next/gpio/gpio.1

Note1:
 - in my setup I don't use u-boot, but UEFI, so I suspect, firmware might clash here: https://github.com/tianocore/edk2-platforms/commit/ee550dd7f240e5eae13a1a37e679a9df3d154681

Note2:
 - there is a recently opened pull request, that suggests testing of Orange Pi 5 setup, so I think, my described problem should not be widely reproducible: https://github.com/jamsinclair/opifancontrol/pull/3

**Comment by dandycyclone** [comment] 2024-06-10 20:48
Update to my previous comment:
 - problem was fully resolved by using PWM1 GPIO (wPI 16) instead of PWM15 (wPI 2):

```
root@pve:~# gpio readall
 +------+-----+----------+--------+---+   OPI5   +---+--------+----------+-----+------+
 | GPIO | wPi |   Name   |  Mode  | V | Physical | V |  Mode  | Name     | wPi | GPIO |
 +------+-----+----------+--------+---+----++----+---+--------+----------+-----+------+
 |      |     |     3.3V |        |   |  1 || 2  |   |        | 5V       |     |      |
 |   47 |   0 |    SDA.5 |     IN | 1 |  3 || 4  |   |        | 5V       |     |      |
 |   46 |   1 |    SCL.5 |     IN | 1 |  5 || 6  |   |        | GND      |     |      |
 |   54 |   2 |    PWM15 |     IN | 1 |  7 || 8  | 0 | IN     | RXD.0    | 3   | 131  |
 |      |     |      GND |        |   |  9 || 10 | 0 | IN     | TXD.0    | 4   | 132  |
 |  138 |   5 |  CAN1_RX |     IN | 1 | 11 || 12 | 1 | IN     | CAN2_TX  | 6   | 29   |
 |  139 |   7 |  CAN1_TX |     IN | 1 | 13 || 14 |   |        | GND      |     |      |
 |   28 |   8 |  CAN2_RX |     IN | 1 | 15 || 16 | 1 | IN     | SDA.1    | 9   | 59   |
 |      |     |     3.3V |        |   | 17 || 18 | 1 | IN     | SCL.1    | 10  | 58   |
 |   49 |  11 | SPI4_TXD |     IN | 1 | 19 || 20 |   |        | GND      |     |      |
 |   48 |  12 | SPI4_RXD |     IN | 1 | 21 || 22 | 1 | IN     | GPIO2_D4 | 13  | 92   |
 |   50 |  14 | SPI4_CLK |     IN | 1 | 23 || 24 | 1 | IN     | SPI4_CS1 | 15  | 52   |
 |      |     |      GND |        |   | 25 || 26 | 0 | ALT11  | PWM1     | 16  | 35   |
 +------+-----+----------+--------+---+----++----+---+--------+----------+-----+------+
 | GPIO | wPi |   Name   |  Mode  | V | Physical | V |  Mode  | Name     | wPi | GPIO |
 +------+-----+----------+--------+---+   OPI5   +---+--------+----------+-----+------+
```

**Comment by xsetiadi** [comment] 2024-08-02 22:25
im got this error:

sudo systemctl status opifancontrol.service
× opifancontrol.service - Orange Pi Fan Control Service
     Loaded: loaded (/etc/systemd/system/opifancontrol.service; enabled; preset: enabled)
     Active: failed (Result: exit-code) since Sat 2024-08-03 05:21:26 WIB; 3min 19s ago
   Duration: 5ms
    Process: 5656 ExecStart=/usr/local/bin/opifancontrol.sh (code=exited, status=203/EXEC)
   Main PID: 5656 (code=exited, status=203/EXEC)
        CPU: 2ms

Aug 03 05:21:26 OPI5Setiadi systemd[1]: opifancontrol.service: Scheduled restart job, restart counter is at 5.
Aug 03 05:21:26 OPI5Setiadi systemd[1]: opifancontrol.service: Start request repeated too quickly.
Aug 03 05:21:26 OPI5Setiadi systemd[1]: opifancontrol.service: Failed with result 'exit-code'.
Aug 03 05:21:26 OPI5Setiadi systemd[1]: Failed to start opifancontrol.service - Orange Pi Fan Control Service.

is this because of my fan is 12V?

**Comment by jamsinclair** [comment] 2024-08-03 04:49
Hey @xsetiadi, thanks for posting.

I think the error is likely from misconfigured GPIO library setup. It would help if you could please post the full log? This can be output with the command

```
sudo journalctl -u opifancontrol
```

> is this because of my fan is 12V?

I don't think this is the cause of the error, but this does create problems.

A 12V fan won't really work with the Orange Pi 5 as it operates at 5V. If you're lucky your fan might run at a slow speed or it may not run at all. You would need a 5V to 12V step-up converter to get it working correctly. You are better off trying to source a 5V fan.

**Comment by xsetiadi** [comment] 2024-08-03 21:02
I got active and function of opifancontrol.service now

there's some inconsistency in your manual tutorial.

in tutorial, it says to copy opifancontrol.sh script to /usr/local/bin/ as opifancontrol

but in your opifancontrol.service when I look into it it refers to /usr/local/bin/opifancontrol.sh

but when I try command: "sudo journalctl -u opifancontrol" I'm still get this error

Aug 03 05:16:07 OPI5Setiadi systemd[1]: Started opifancontrol.service - Orange Pi Fan Control Service.
Aug 03 05:16:07 OPI5Setiadi systemd[1]: opifancontrol.service: Main process exited, code=exited, status=203/EXEC
Aug 03 05:16:07 OPI5Setiadi systemd[1]: opifancontrol.service: Failed with result 'exit-code'.
Aug 03 05:16:07 OPI5Setiadi systemd[1]: opifancontrol.service: Scheduled restart job, restart counter is at 1.
Aug 03 05:16:07 OPI5Setiadi systemd[1]: Started opifancontrol.service - Orange Pi Fan Control Service.
Aug 03 05:16:07 OPI5Setiadi systemd[1]: opifancontrol.service: Main process exited, code=exited, status=203/EXEC
Aug 03 05:16:07 OPI5Setiadi systemd[1]: opifancontrol.service: Failed with result 'exit-code'.
Aug 03 05:16:08 OPI5Setiadi systemd[1]: opifancontrol.service: Scheduled restart job, restart counter is at 2.
Aug 03 05:16:08 OPI5Setiadi systemd[1]: Started opifancontrol.service - Orange Pi Fan Control Service.
Aug 03 05:16:08 OPI5Setiadi systemd[1]: opifancontrol.service: Main process exited, code=exited, status=203/EXEC
Aug 03 05:16:08 OPI5Setiadi systemd[1]: opifancontrol.service: Failed with result 'exit-code'.
Aug 03 05:16:08 OPI5Setiadi systemd[1]: opifancontrol.service: Scheduled restart job, restart counter is at 3.
Aug 03 05:16:08 OPI5Setiadi systemd[1]: Started opifancontrol.service - Orange Pi Fan Control Service.
Aug 03 05:16:08 OPI5Setiadi systemd[1]: opifancontrol.service: Main process exited, code=exited, status=203/EXEC
Aug 03 05:16:08 OPI5Setiadi systemd[1]: opifancontrol.service: Failed with result 'exit-code'.
Aug 03 05:16:09 OPI5Setiadi systemd[1]: opifancontrol.service: Scheduled restart job, restart counter is at 4.
Aug 03 05:16:09 OPI5Setiadi systemd[1]: Started opifancontrol.service - Orange Pi Fan Control Service.
Aug 03 05:16:09 OPI5Setiadi systemd[1]: opifancontrol.service: Main process exited, code=exited, status=203/EXEC
Aug 03 05:16:09 OPI5Setiadi systemd[1]: opifancontrol.service: Failed with result 'exit-code'.
Aug 03 05:16:09 OPI5Setiadi systemd[1]: opifancontrol.service: Scheduled restart job, restart counter is at 5.
Aug 03 05:16:09 OPI5Setiadi systemd[1]: opifancontrol.service: Start request repeated too quickly.
Aug 03 05:16:09 OPI5Setiadi systemd[1]: opifancontrol.service: Failed with result 'exit-code'.
Aug 03 05:16:09 OPI5Setiadi systemd[1]: Failed to start opifancontrol.service - Orange Pi Fan Control Service.
Aug 03 05:17:53 OPI5Setiadi systemd[1]: Started opifancontrol.service - Orange Pi Fan Control Service.
Aug 03 05:17:53 OPI5Setiadi systemd[1]: opifancontrol.service: Main process exited, code=exited, status=203/EXEC
Aug 03 05:17:53 OPI5Setiadi systemd[1]: opifancontrol.service: Failed with result 'exit-code'.
Aug 03 05:17:53 OPI5Setiadi systemd[1]: opifancontrol.service: Scheduled restart job, restart counter is at 1.
Aug 03 05:17:53 OPI5Setiadi systemd[1]: Started opifancontrol.service - Orange Pi Fan Control Service.
Aug 03 05:17:53 OPI5Setiadi systemd[1]: opifancontrol.service: Main process exited, code=exited, status=203/EXEC
Aug 03 05:17:53 OPI5Setiadi systemd[1]: opifancontrol.service: Failed with result 'exit-code'.
Aug 03 05:17:54 OPI5Setiadi systemd[1]: opifancontrol.service: Scheduled restart job, restart counter is at 2.
Aug 03 05:17:54 OPI5Setiadi systemd[1]: Started opifancontrol.service - Orange Pi Fan Control Service.
Aug 03 05:17:54 OPI5Setiadi systemd[1]: opifancontrol.service: Main process exited, code=exited, status=203/EXEC
Aug 03 05:17:54 OPI5Setiadi systemd[1]: opifancontrol.service: Failed with result 'exit-code'.
Aug 03 05:17:54 OPI5Setiadi systemd[1]: opifancontrol.service: Scheduled restart job, restart counter is at 3.
Aug 03 05:17:54 OPI5Setiadi systemd[1]: Started opifancontrol.service - Orange Pi Fan Control Service.
Aug 03 05:17:54 OPI5Setiadi systemd[1]: opifancontrol.service: Main process exited, code=exited, status=203/EXEC
Aug 03 05:17:54 OPI5Setiadi systemd[1]: opifancontrol.service: Failed with result 'exit-code'.
Aug 03 05:17:54 OPI5Setiadi systemd[1]: opifancontrol.service: Scheduled restart job, restart counter is at 4.
Aug 03 05:17:54 OPI5Setiadi systemd[1]: Started opifancontrol.service - Orange Pi Fan Control Service.
Aug 03 05:17:54 OPI5Setiadi systemd[1]: opifancontrol.service: Main process exited, code=exited, status=203/EXEC
Aug 03 05:17:54 OPI5Setiadi systemd[1]: opifancontrol.service: Failed with result 'exit-code'.
Aug 03 05:17:54 OPI5Setiadi systemd[1]: opifancontrol.service: Scheduled restart job, restart counter is at 5.
Aug 03 05:17:54 OPI5Setiadi systemd[1]: opifancontrol.service: Start request repeated too quickly.
Aug 03 05:17:54 OPI5Setiadi systemd[1]: opifancontrol.service: Failed with result 'exit-code'.

**Comment by xsetiadi** [comment] 2024-08-03 21:05
actually my 12V fan is better than the original 5V from 52pi ice tower. im use that heatsink on my opi5. and now despite this fan is not run on full speed. but with 5V from GPIO its really fine.

and also in here I change the PWM gpio to (wpi16) like suggestion from dandycyclone in /etc/opifancontrol.conf and inside /usr/local/bin/opifancontrol

**Comment by xsetiadi** [comment] 2024-08-04 09:24
i think its working now, after restart my system. I'm not able to restart yesterday because I have a download file running on jdownloader2, but after I'm restart my opi5 today no error. and "sudo journalctl -u opifancontrol" show this

xsetiadi@OPI5Setiadi:~$ sudo journalctl -u opifancontrol
Aug 04 16:18:36 OPI5Setiadi systemd[1]: Started opifancontrol.service - Orange Pi Fan Control Service.
Aug 04 16:18:36 OPI5Setiadi opifancontrol.sh[4520]: Starting opifancontrol (v1.0.2) ...
Aug 04 16:18:36 OPI5Setiadi opifancontrol.sh[4520]: PWM range: 192
Aug 04 16:18:36 OPI5Setiadi opifancontrol.sh[4520]: PWM clock: 4
Aug 04 16:18:36 OPI5Setiadi opifancontrol.sh[4520]: Fan GPIO pin: 16
Aug 04 16:18:36 OPI5Setiadi opifancontrol.sh[4520]: Temperature poll interval: 2 seconds
Aug 04 16:18:36 OPI5Setiadi opifancontrol.sh[4520]: Temperature thresholds (C): 37, 39, 40
Aug 04 16:18:36 OPI5Setiadi systemd[1]: Started opifancontrol.service - Orange Pi Fan Control Service.
Aug 04 16:18:36 OPI5Setiadi opifancontrol.sh[4520]: Starting opifancontrol (v1.0.2) ...
Aug 04 16:18:36 OPI5Setiadi opifancontrol.sh[4520]: PWM range: 192
Aug 04 16:18:36 OPI5Setiadi opifancontrol.sh[4520]: PWM clock: 4
Aug 04 16:18:36 OPI5Setiadi opifancontrol.sh[4520]: Fan GPIO pin: 16
Aug 04 16:18:36 OPI5Setiadi opifancontrol.sh[4520]: Temperature poll interval: 2 seconds
Aug 04 16:18:36 OPI5Setiadi opifancontrol.sh[4520]: Temperature thresholds (C): 37, 39, 40
Aug 04 16:18:36 OPI5Setiadi opifancontrol.sh[4520]: Fan speed thresholds (%): 50, 75, 100
Aug 04 16:18:36 OPI5Setiadi opifancontrol.sh[4520]: Ramp up delay: 15 seconds
Aug 04 16:18:36 OPI5Setiadi opifancontrol.sh[4520]: Ramp down delay: 60 seconds
Aug 04 16:18:36 OPI5Setiadi opifancontrol.sh[4520]: Debugging enabled
Aug 04 16:18:36 OPI5Setiadi opifancontrol.sh[4520]: Changing Fan Speed | CPU temp: 41, target PWM: 192, current PWM>
Aug 04 16:18:39 OPI5Setiadi opifancontrol.sh[4520]: Changing Fan Speed | CPU temp: 39, target PWM: 144, current PWM>
Aug 04 16:18:46 OPI5Setiadi opifancontrol.sh[4520]: Changing Fan Speed | CPU temp: 38, target PWM: 96, current PWM:>
Aug 04 16:19:43 OPI5Setiadi opifancontrol.sh[4520]: Delay of 60 sec before turning off the fan ... Target PWM: 0
Aug 04 16:20:43 OPI5Setiadi opifancontrol.sh[4520]: Turning off the fan
Aug 04 16:20:43 OPI5Setiadi opifancontrol.sh[4520]: Changing Fan Speed | CPU temp: 36, target PWM: 0, current PWM: >
Aug 04 16:21:15 OPI5Setiadi opifancontrol.sh[4520]: Exiting opifancontrol and setting fan pin to 0 PWM
Aug 04 16:21:15 OPI5Setiadi systemd[1]: Stopping opifancontrol.service - Orange Pi Fan Control Service...
Aug 04 16:21:15 OPI5Setiadi opifancontrol.sh[4520]: Terminated
Aug 04 16:21:15 OPI5Setiadi systemd[1]: opifancontrol.service: Deactivated successfully.
Aug 04 16:21:15 OPI5Setiadi systemd[1]: Stopped opifancontrol.service - Orange Pi Fan Control Service.
Aug 04 16:21:15 OPI5Setiadi systemd[1]: opifancontrol.service: Consumed 1.054s CPU time, 2.1M memory peak.
Aug 04 16:21:15 OPI5Setiadi systemd[1]: Started opifancontrol.service - Orange Pi Fan Control Service.
Aug 04 16:21:15 OPI5Setiadi opifancontrol.sh[6005]: Starting opifancontrol (v1.0.2) ...
Aug 04 16:21:15 OPI5Setiadi opifancontrol.sh[6005]: PWM range: 192
Aug 04 16:21:15 OPI5Setiadi opifancontrol.sh[6005]: PWM clock: 4
Aug 04 16:21:15 OPI5Setiadi opifancontrol.sh[6005]: Fan GPIO pin: 16
lines 1-28/35 80%...skipping...
Aug 04 16:18:36 OPI5Setiadi systemd[1]: Started opifancontrol.service - Orange Pi Fan Control Service.
Aug 04 16:18:36 OPI5Setiadi opifancontrol.sh[4520]: Starting opifancontrol (v1.0.2) ...
Aug 04 16:18:36 OPI5Setiadi opifancontrol.sh[4520]: PWM range: 192
Aug 04 16:18:36 OPI5Setiadi opifancontrol.sh[4520]: PWM clock: 4
Aug 04 16:18:36 OPI5Setiadi opifancontrol.sh[4520]: Fan GPIO pin: 16
Aug 04 16:18:36 OPI5Setiadi opifancontrol.sh[4520]: Temperature poll interval: 2 seconds
Aug 04 16:18:36 OPI5Setiadi opifancontrol.sh[4520]: Temperature thresholds (C): 37, 39, 40
Aug 04 16:18:36 OPI5Setiadi opifancontrol.sh[4520]: Fan speed thresholds (%): 50, 75, 100
Aug 04 16:18:36 OPI5Setiadi opifancontrol.sh[4520]: Ramp up delay: 15 seconds
Aug 04 16:18:36 OPI5Setiadi opifancontrol.sh[4520]: Ramp down delay: 60 seconds
Aug 04 16:18:36 OPI5Setiadi opifancontrol.sh[4520]: Debugging enabled
Aug 04 16:18:36 OPI5Setiadi opifancontrol.sh[4520]: Changing Fan Speed | CPU temp: 41, target PWM: 192, current PWM>
Aug 04 16:18:39 OPI5Setiadi opifancontrol.sh[4520]: Changing Fan Speed | CPU temp: 39, target PWM: 144, current PWM>
Aug 04 16:18:46 OPI5Setiadi opifancontrol.sh[4520]: Changing Fan Speed | CPU temp: 38, target PWM: 96, current PWM:>
Aug 04 16:19:43 OPI5Setiadi opifancontrol.sh[4520]: Delay of 60 sec before turning off the fan ... Target PWM: 0
Aug 04 16:20:43 OPI5Setiadi opifancontrol.sh[4520]: Turning off the fan
Aug 04 16:20:43 OPI5Setiadi opifancontrol.sh[4520]: Changing Fan Speed | CPU temp: 36, target PWM: 0, current PWM: >
Aug 04 16:21:15 OPI5Setiadi opifancontrol.sh[4520]: Exiting opifancontrol and setting fan pin to 0 PWM
Aug 04 16:21:15 OPI5Setiadi systemd[1]: Stopping opifancontrol.service - Orange Pi Fan Control Service...
Aug 04 16:21:15 OPI5Setiadi opifancontrol.sh[4520]: Terminated
Aug 04 16:21:15 OPI5Setiadi systemd[1]: opifancontrol.service: Deactivated successfully.
Aug 04 16:21:15 OPI5Setiadi systemd[1]: Stopped opifancontrol.service - Orange Pi Fan Control Service.
Aug 04 16:21:15 OPI5Setiadi systemd[1]: opifancontrol.service: Consumed 1.054s CPU time, 2.1M memory peak.
Aug 04 16:21:15 OPI5Setiadi systemd[1]: Started opifancontrol.service - Orange Pi Fan Control Service.
Aug 04 16:21:15 OPI5Setiadi opifancontrol.sh[6005]: Starting opifancontrol (v1.0.2) ...
Aug 04 16:21:15 OPI5Setiadi opifancontrol.sh[6005]: PWM range: 192
Aug 04 16:21:15 OPI5Setiadi opifancontrol.sh[6005]: PWM clock: 4
Aug 04 16:21:15 OPI5Setiadi opifancontrol.sh[6005]: Fan GPIO pin: 16
Aug 04 16:21:15 OPI5Setiadi opifancontrol.sh[6005]: Temperature poll interval: 2 seconds
Aug 04 16:21:15 OPI5Setiadi opifancontrol.sh[6005]: Temperature thresholds (C): 35, 37, 39
Aug 04 16:21:15 OPI5Setiadi opifancontrol.sh[6005]: Fan speed thresholds (%): 50, 75, 100
Aug 04 16:21:15 OPI5Setiadi opifancontrol.sh[6005]: Ramp up delay: 15 seconds
Aug 04 16:21:15 OPI5Setiadi opifancontrol.sh[6005]: Ramp down delay: 60 seconds
Aug 04 16:21:15 OPI5Setiadi opifancontrol.sh[6005]: Debugging enabled
Aug 04 16:21:15 OPI5Setiadi opifancontrol.sh[6005]: Changing Fan Speed | CPU temp: 36, target PWM: 96, current PWM:>
~

**Comment by dandycyclone** [comment] 2024-08-04 09:55
Thank you for feedback, @xsetiadi .
@jamsinclair , I suppose, you can close this issue, since original concern was addressed some time ago: #3 

> Hi! Great job. But I only have an orange pi 5. Does it work for it? Have a nice day

**Note:**
 - if you decide so, you can also fix the typo in the README (installation/update via [install.sh](https://github.com/jamsinclair/opifancontrol/blob/main/install.sh) does not have this problem):

```
in tutorial, it says to copy opifancontrol.sh script to /usr/local/bin/ as opifancontrol
but in your opifancontrol.service when I look into it it refers to /usr/local/bin/opifancontrol.sh
```

**Comment by xsetiadi** [comment] 2024-08-05 00:01
but when my temp is belom the LOW_TEMP the fan keep spinning. not turn off is this normal? maybe there is something wrong with my fan.

**Comment by jamsinclair** [comment] 2024-08-05 04:39
Thanks @dandycyclone. I've updated with the manual installation instructions 👍 

> when my temp is belom the LOW_TEMP the fan keep spinning. not turn off is this normal?

@xsetiadi There is logic to keep the fan spinning for a duration of time after it's below the `LOW_TEMP`. This is to avoid the fan turning on and off frequently.

The default is 60 seconds. You can change the `RAMP_DOWN_DELAY_SECONDS` value in the config. [Please see the README instructions](https://github.com/jamsinclair/opifancontrol?tab=readme-ov-file#configuration).

I'll close this ticket now as I think we've resolved the original ticket purpose.

**Closed as completed by jamsinclair** 2024-08-05 04:39 UTC
